export CUDA_VISIBLE_DEVICES=0
cd ..
python -u run.py \
    --is_training 1 \
    --device cpu \
    --dataset_name ucf101 \
    --train_data_paths /Users/mubeenqaiser/Documents/Datasets/UCF101/ucf101-train.npz \
    --valid_data_paths /Users/mubeenqaiser/Documents/Datasets/UCF101/ucf101-val.npz \
    --save_dir checkpoints/ucf101_predrnn \
    --gen_frm_dir results/ucf101_predrnn \
    --model_name predrnn \
    --reverse_input 1 \
    --img_width 64 \
    --img_channel 1 \
    --input_length 10 \
    --total_length 20 \
    --num_hidden 128,128,128,128 \
    --filter_size 5 \
    --stride 1 \
    --patch_size 4 \
    --layer_norm 0 \
    --scheduled_sampling 1 \
    --sampling_stop_iter 50000 \
    --sampling_start_value 1.0 \
    --sampling_changing_rate 0.00002 \
    --lr 0.0001 \
    --batch_size 4 \
    --max_iterations 20 \
    --display_interval 1 \
    --test_interval 20 \
    --snapshot_interval 1 \
    --loss_filename ucf101_loss